# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: h:/labs_Vivado/lab09_ver2/lab09_ver2.srcs/sources_1/ip/char_buf/char_buf.xci
# IP: The module: 'char_buf' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/labs_Vivado/lab09_ver2/lab09_ver2.gen/sources_1/ip/char_buf/char_buf_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'char_buf'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: h:/labs_Vivado/lab09_ver2/lab09_ver2.srcs/sources_1/ip/char_buf/char_buf.xci
# IP: The module: 'char_buf' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/labs_Vivado/lab09_ver2/lab09_ver2.gen/sources_1/ip/char_buf/char_buf_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'char_buf'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
