# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: H:/DigitalLab/lab08/nexysa7-lab8.xdc

# IP: ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet
